micronaut:
  application:
    name: mnHackernewsClone
  server:
    port: 8100
  router:
    versioning:
      enable: true
      default-version: 1
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  metrics:
    enabled: true
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    interceptUrlMap:
      -
        pattern: "/swagger-ui/**"
        httpMethod: GET
        access:
          - isAnonymous()
      -
        pattern: "/swagger/**"
        httpMethod: GET
        access:
          - isAnonymous()
      -
        pattern: "/rapidoc/**"
        httpMethod: GET
        access:
          - isAnonymous()
      -
        pattern: "/redoc/**"
        httpMethod: GET
        access:
          - isAnonymous()
endpoints:
  all:
    enabled: true
    sensitive: false
  stop:
    enabled: false

person:
  controller:
    path: "/persons"
  service:
    greeting: "Hello From Service 2"

datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update

jpa:
  default:
    entity-scan:
      packages: 'br.com.everis.model.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true